version: '3'

services:
#  sqlite3:
#    container_name: db
#    image: nouchka/sqlite3:latest
#    stdin_open: true
#    tty: true
#    volumes:
#      - ./db:/root/db/
  webapp:
    container_name: webapp
    build:
      context: ./
    volumes:
      - ./app:/src
    env_file:
      - ./src/src/.env
    ports:
      - "8000:8000"
    command: >
      sh -c "python ./src/manage.py makemigrations && 
             python ./src/manage.py migrate &&
             python ./src/manage.py runserver 0.0.0.0:8000"
#    depends_on:
#      - sqlite3